### ISSUE TITLE
JS Test Failures for d3 3.4.13

### ISSUE THREAD

**Issue by etgalloway** [mpld3/mpld3#374]
mpld3's JS tests pass on Travis for Node 0.10 but fail for Node versions 0.11, 0.12, 3 (io.js),
4, 5, and 6.

git master's tests pass on Travis because Travis defaults to Node 0.10.36 (currently) for
Python projects.

The JS tests use d3 3.4.13, the version of d3 installed by npm. (This is not the version
that is currently bundled with git master; package.json needs to be updated).

The `.travis.yml` file used for the JS tests:
```
    language: node_js
    node_js:
      - "6"
      - "5"
      - "4"
      - "0.12"
      - "0.11"
      - "0.10"
      - "iojs"
    env:
      - CXX=g++-4.8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
```
